let constants = {
	SUBMIT_QUESTION: "SUBMIT_QUESTION",
	DELETE_QUESTION: "DELETE_QUESTION",
	EDITING_QUESTION: "EDITING_QUESTION",
	UPDATE_QUESTION: "UPDATE_QUESTION",
	UPVOTE_QUESTION: "UPVOTE_QUESTION",
	DOWNVOTE_QUESTION: "DOWNVOTE_QUESTION",
	DISPLAY_QUESTIONS: "DISPLAY_QUESTIONS",
	FILTER_QUESTIONS: "FILTER_QUESTIONS",
	//ANSWERS
	SUBMIT_ANSWER: "SUBMIT_ANSWER",
	EDITING_ANSWER: "EDITING_ANSWER",
	UPDATE_ANSWER: "UPDATE_ANSWER",
	//approval status
	QUESTION_PENDING: "QUESTION_PENDING",
	QUESTION_APPROVED: "QUESTION_APPROVED",
	QUESTION_REJECTED: "QUESTION_REJECTED",
	APPROVE_QUESTION: "APPROVE_QUESTION",
	REJECT_QUESTION: "REJECT_QUESTION",
	//PROFILES
	SUBMIT_PROFILE: "SUBMIT_PROFILE",
	DISPLAY_PROFILE: "DISPLAY_PROFILE",
	//API
	API_QUESTIONS: "http://localhost:3030/api/questions/",
	API_QUESTION: "http://localhost:3030/api/question/",
	API_PROFILES: "http://localhost:3030/api/profiles/",
	API_PROFILE: "http://localhost:3030/api/profile/",
	REQUESTING: "REQUESTING",
	REQUEST_SUCCESS: "REQUEST_SUCCESS",
	REQUEST_ERROR: "REQUEST_ERROR"
	
}

export default constants