let constants = {
	SUBMIT_QUESTION: "SUBMIT_QUESTION",
	DELETE_QUESTION: "DELETE_QUESTION",
	EDIT_QUESTION: "EDIT_QUESTION",
	UPVOTE_QUESTION: "UPVOTE_QUESTION",
	DOWNVOTE_QUESTION: "DOWNVOTE_QUESTION",
	DISPLAY_QUESTIONS: "DISPLAY_QUESTIONS",
	SUBMIT_ANSWER: "SUBMIT_ANSWER",
	EDIT_ANSWER: "EDIT_ANSWER",
	NOT_EDITING_ANSWER: "NOT_EDITING_ANSWER",
	//approval status
	QUESTION_PENDING: "QUESTION_PENDING",
	QUESTION_APPROVED: "QUESTION_APPROVED",
	QUESTION_REJECTED: "QUESTION_REJECTED",
	APPROVE_QUESTION: "APPROVE_QUESTION",
	REJECT_QUESTION: "REJECT_QUESTION",
	//API
	API_QUESTIONS: "http://localhost:3030/api/questions/",
	API_QUESTION: "http://localhost:3030/api/question/",
	REQUESTING: "REQUESTING",
	REQUEST_SUCCESS: "REQUEST_SUCCESS",
	REQUEST_ERROR: "REQUEST_ERROR"
	
}

export default constants