let constants = {
	SUBMIT_QUESTION: "SUBMIT_QUESTION",
	DELETE_QUESTION: "DELETE_QUESTION",
	EDIT_QUESTON: "EDIT_QUESTION",
	UPVOTE_QUESTION: "UPVOTE_QUESTION",
	DOWNVOTE_QUESTION: "DOWNVOTE_QUESTION",

	DISPLAY_QUESTIONS: "DISPLAY_QUESTIONS"
}

export default constants